version: "3"
services:
  web:
    image: yadachi/get-started:part2
    deploy:
      # 1 service consists of 5 containers.
      replicas: 5
      resources:
          limits:
            cpus: "0.1"
            memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
  # Visualizer
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    # giving the visualizer access to the hots's socket file for Docker
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      # ensuring that this service only ever runs on a swarm manager.
      placement:
        constraints: [node.role == manager]
    networks: 
      - webnet
  # Redis
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - "/home/docker/data:/data"
    deploy:
      placement:
        constraints: [node.role == manager]
    command: redis-server --appendonly yes
    networks: 
      - webnet
networks: 
  webnet: