version: "3"
services:
  web:
    image: yadachi/get-started:part2
    deploy:
      # 1 service consists of 5 containers.
      replicas: 6
      resources:
          limits:
            cpus: "0.1"
            memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
networks: 
  webnet: